#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
/home/anthonygay1812/OpenFOAM/root-7/platforms/linux64GccDPInt32Opt/bin/dsmcInitialiseMod > log.dsmcInitialiseMod
/home/anthonygay1812/OpenFOAM/root-7/platforms/linux64GccDPInt32Opt/bin/dsmcFoamMod > log.dsmcFoamMod
#runApplication dsmcInitialise
#runApplication $(getApplication)
#------------------------------------------------------------------------------
