#!/bin/sh
cd $HOME/OpenFOAM/Working/DSMC_mod
wclean
wmake libso
cd $HOME/OpenFOAM/Working/dsmcInitialise_modified
wclean
wmake
cd $HOME/OpenFOAM/Working/dsmcFoam_modified
wclean
wmake
cd $HOME/OpenFOAM/Working/dsmcShockTube