#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf constant/fluid/polyMesh constant/particle/polyMesh 0/particle/lagrangian 0/particle/dsmcSigmaTcRMax 0/particle/uniform > /dev/null 2>&1

#------------------------------------------------------------------------------
