#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
#rm -rf /home/anthonygay1812/OpenFOAM/Working/finalShockTube/constant/polyMesh
runApplication splitMeshRegions -cellZonesOnly -overwrite
#runApplication decomposePar -allRegions
#runApplication setFields -region fluid
#runParallel $(getApplication)
runApplication $(getApplication)
#runApplication reconstructPar -allRegions
paraFoam -touchAll

#------------------------------------------------------------------------------
