#!/bin/sh
cd $HOME/OpenFOAM/Working/dsmcMod2
wclean
wmake libso
cd $HOME/OpenFOAM/Working/dsmcInitialiseMod2
wclean
wmake
cd $HOME/OpenFOAM/Working/dsmcFoamMod2
wclean
wmake
cd $HOME/OpenFOAM/Working/rhoCentralFoamMod
./Allwclean
./Allwmake
cd $HOME/OpenFOAM/Working/finalShockTube
