#!/bin/sh
cd /home/anthonygay1812/OpenFOAM/Working/DSMC_mod
wclean
wmake libso
cd /home/anthonygay1812/OpenFOAM/Working/dsmcInitialise_modified
wclean
wmake
cd /home/anthonygay1812/OpenFOAM/Working/dsmcFoam_modified
wclean
wmake
cd /home/anthonygay1812/OpenFOAM/Working/dsmcShockTube